window.OilArray = {
    opt0: {
        name: "",
        sap_value_potash: 0,
        sap_value_soda: 0,
        skin: 0,
        clean: 0,
        foam: 0,
        hard: 0,
        collapse: 0,
        stability: 0
    },
    opt1: {
        name: "アプリコット核油",
        sap_value_potash: 194,
        sap_value_soda: 139,
        skin: 8.9,
        clean: 9.3,
        foam: 5.4,
        hard: 4.9,
        collapse: 4.4,
        stability: 5.0
    },
    opt2: {
        name: "アボガド油",
        sap_value_potash: 193,
        sap_value_soda: 139,
        skin: 8.6,
        clean: 9.0,
        foam: 5.4,
        hard: 5.4,
        collapse: 5.1,
        stability: 5.5
    },
    opt3: {
        name: "オリーブオイル",
        sap_value_potash: 191,
        sap_value_soda: 136,
        skin: 8.8,
        clean: 8.9,
        foam: 5.0,
        hard: 5.6,
        collapse: 5.3,
        stability: 5.8
    },
    opt4: {
        name: "キャノーラ油",
        sap_value_potash: 187,
        sap_value_soda: 134,
        skin: 8.6,
        clean: 9.2,
        foam: 5.4,
        hard: 4.0,
        collapse: 3.3,
        stability: 4.0
    },
    opt5: {
        name: "牛脂",
        sap_value_potash: 196,
        sap_value_soda: 140,
        skin: 6.6,
        clean: 6.1,
        foam: 4.5,
        hard: 7.0,
        collapse: 10.1,
        stability: 7.5
    },
    opt6: {
        name: "ククイナッツ油",
        sap_value_potash: 190,
        sap_value_soda: 135,
        skin: 7.8,
        clean: 9.2,
        foam: 6.3,
        hard: 1.8,
        collapse: 2.0,
        stability: 1.9
    },
    opt7: {
        name: "くるみ油",
        sap_value_potash: 194,
        sap_value_soda: 135,
        skin: 7.9,
        clean: 9.2,
        foam: 6.3,
        hard: 2.0,
        collapse: 2.5,
        stability: 2.1
    },
    opt8: {
        name: "グレープシード油",
        sap_value_potash: 188,
        sap_value_soda: 139,
        skin: 7.6,
        clean: 8.7,
        foam: 6.0,
        hard: 2.6,
        collapse: 3.6,
        stability: 2.8
    },
    opt9: {
        name: "ココアバター",
        sap_value_potash: 201,
        sap_value_soda: 137,
        skin: 6.3,
        clean: 5.0,
        foam: 3.3,
        hard: 7.5,
        collapse: 12.2,
        stability: 8.1
    },
    opt10: {
        name: "ココナッツ油",
        sap_value_potash: 258,
        sap_value_soda: 181,
        skin: 2.7,
        clean: 5.6,
        foam: 13.6,
        hard: 8.6,
        collapse: 6.8,
        stability: 8.2
    },
    opt11: {
        name: "小麦胚芽油",
        sap_value_potash: 185,
        sap_value_soda: 130,
        skin: 7.3,
        clean: 8.5,
        foam: 6.1,
        hard: 2.8,
        collapse: 3.9,
        stability: 3.0
    },
    opt12: {
        name: "米ぬか油",
        sap_value_potash: 188,
        sap_value_soda: 128,
        skin: 7.7,
        clean: 8.5,
        foam: 5.7,
        hard: 4.1,
        collapse: 4.9,
        stability: 4.3
    },
    opt13: {
        name: "コーン油",
        sap_value_potash: 193,
        sap_value_soda: 136,
        skin: 7.9,
        clean: 8.9,
        foam: 6.0,
        hard: 3.2,
        collapse: 3.7,
        stability: 3.3
    },
    opt14: {
        name: "ごま油",
        sap_value_potash: 186,
        sap_value_soda: 133,
        skin: 8.1,
        clean: 8.8,
        foam: 5.6,
        hard: 3.6,
        collapse: 4.1,
        stability: 3.8
    },
    opt15: {
        name: "シアバター",
        sap_value_potash: 187,
        sap_value_soda: 129,
        skin: 7.8,
        clean: 6.3,
        foam: 3.0,
        hard: 6.9,
        collapse: 10.0,
        stability: 7.3
    },
    opt16: {
        name: "ｽｲｰﾄｱｰﾓﾝﾄﾞｵｲﾙ",
        sap_value_potash: 194,
        sap_value_soda: 139,
        skin: 8.7,
        clean: 9.1,
        foam: 5.2,
        hard: 4.7,
        collapse: 4.1,
        stability: 4.8
    },
    opt17: {
        name: "ステアリン酸",
        sap_value_potash: 189,
        sap_value_soda: 141,
        skin: 6.0,
        clean: 2.0,
        foam: 0.0,
        hard: 9.0,
        collapse: 18.0,
        stability: 10.0
    },
    opt18: {
        name: "月見草油",
        sap_value_potash: 188,
        sap_value_soda: 136,
        skin: 7.8,
        clean: 9.4,
        foam: 6.5,
        hard: 1.4,
        collapse: 1.9,
        stability: 1.5
    },
    opt19: {
        name: "椿油",
        sap_value_potash: 193,
        sap_value_soda: 136,
        skin: 9.2,
        clean: 9.2,
        foam: 5.0,
        hard: 6.0,
        collapse: 5.3,
        stability: 6.1
    },
    opt20: {
        name: "バター(乳脂)",
        sap_value_potash: 196,
        sap_value_soda: 161,
        skin: 6.0,
        clean: 6.4,
        foam: 6.2,
        hard: 7.3,
        collapse: 9.9,
        stability: 7.9
    },
    opt21: {
        name: "馬油",
        sap_value_potash: 200,
        sap_value_soda: 140,
        skin: 7.0,
        clean: 7.3,
        foam: 5.5,
        hard: 5.7,
        collapse: 7.6,
        stability: 6.0
    },
    opt22: {
        name: "パーム油",
        sap_value_potash: 203,
        sap_value_soda: 141,
        skin: 6.0,
        clean: 6.1,
        foam: 5.1,
        hard: 6.8,
        collapse: 10.3,
        stability: 7.3
    },
    opt23: {
        name: "パーム核油",
        sap_value_potash: 249,
        sap_value_soda: 156,
        skin: 3.8,
        clean: 6.6,
        foam: 14.0,
        hard: 8.5,
        collapse: 7.0,
        stability: 8.6
    },
    opt24: {
        name: "ひまし油",
        sap_value_potash: 182,
        sap_value_soda: 130,
        skin: 8.1,
        clean: 2.9,
        foam: 0.7,
        hard: 10.4,
        collapse: 0.8,
        stability: 6.0
    },
    opt25: {
        name: "ひまわり油",
        sap_value_potash: 190,
        sap_value_soda: 134,
        skin: 9.3,
        clean: 9.2,
        foam: 4.9,
        hard: 5.7,
        collapse: 4.9,
        stability: 5.8
    },
    opt26: {
        name: "ヘーゼルナッツ油",
        sap_value_potash: 188,
        sap_value_soda: 136,
        skin: 7.4,
        clean: 7.6,
        foam: 4.5,
        hard: 4.3,
        collapse: 3.3,
        stability: 4.3
    },
    opt27: {
        name: "紅花油",
        sap_value_potash: 190,
        sap_value_soda: 136,
        skin: 9.1,
        clean: 9.4,
        foam: 5.2,
        hard: 5.3,
        collapse: 4.5,
        stability: 5.4
    },
    opt28: {
        name: "ホホバオイル",
        sap_value_potash: 92,
        sap_value_soda: 66,
        skin: 6.8,
        clean: 5.5,
        foam: 2.1,
        hard: 5.1,
        collapse: 0.8,
        stability: 5.1
    },
    opt29: {
        name: "マカデミアナッツ油",
        sap_value_potash: 195,
        sap_value_soda: 139,
        skin: 8.3,
        clean: 8.3,
        foam: 5.0,
        hard: 5.6,
        collapse: 5.0,
        stability: 5.7
    },
    opt30: {
        name: "みつろう",
        sap_value_potash: 91,
        sap_value_soda: 69,
        skin: 2.0,
        clean: 1.9,
        foam: 4.7,
        hard: 8.6,
        collapse: 17.3,
        stability: 9.6
    },
    opt31: {
        name: "落花生油",
        sap_value_potash: 193,
        sap_value_soda: 188,
        skin: 7.7,
        clean: 8.3,
        foam: 5.4,
        hard: 3.9,
        collapse: 4.4,
        stability: 4.0
    },
    opt32: {
        name: "ラード(豚油)",
        sap_value_potash: 198,
        sap_value_soda: 138,
        skin: 7.4,
        clean: 7.9,
        foam: 6.6,
        hard: 7.4,
        collapse: 9.9,
        stability: 7.9
    },
    opt33: {
        name: "ローズヒップオイル",
        sap_value_potash: 190,
        sap_value_soda: 138,
        skin: 7.9,
        clean: 9.4,
        foam: 6.4,
        hard: 1.3,
        collapse: 1.6,
        stability: 1.4
    },

};